exports.queryList = {
    
    GET_ALL_PRODUCTS_ORDER : `SELECT PRODUCT_PRICE FROM ECOMERCE.ORDER_PRODUCTS 
    INNER JOIN  ECOMERCE.PRODUCTS ON PRODUCTS.PRODUCT_ID =ORDER_PRODUCTS.PRODUCT_ID WHERE ORDER_PRODUCTS.ORDER_ID =($1)  `,
   
    GET_orders_DETAIL_QUERY : `SELECT users.username,orders.order_address,orders.order_distance,orders.products_total
    ,orders.order_price_total,orders.order_status,orders.delivery_fees
    FROM ecomerce.orders inner join ecomerce.users on orders.user_id = users.user_id
    where orders.order_status != '' $1
    ORDER BY order_id ASC  
    LIMIT 1 OFFSET 0;`,
    
    SAVE_PRODUCT_QUERY : `INSERT INTO ECOMERCE.PRODUCTS (PRODUCT_NAME , PRODUCT_DETAILS , PRODUCT_CODE , PRODUCT_PRICE,CREATED_ON)
                        VALUES($1, $2, $3, $4, $5 ) `,


    SET_NEW_ORDER : `
                    UPDATE ECOMERCE.ORDERS SET ORDER_STATUS='new', ORDER_SUBMIT=1, ORDER_PRICE_TOTAL=$1, PRODUCTS_TOTAL=$2, 
                    ORDER_ADDRESS=$3, ORDER_DISTANCE=$4 ,DELIVERY_FEES = $6
                    WHERE ORDER_ID=$5
    `,


    SET_PRODUCT_IN_ORDER :`INSERT INTO ECOMERCE.ORDER_PRODUCTS (ORDER_ID,PRODUCT_ID,CREATED_ON) VALUES($1, $2,$3)`,
    SET_INTIAL_ORDER :`INSERT INTO ECOMERCE.ORDERS (USER_ID,CREATED_ON) VALUES($1, $2)`,
    GET_ORDERS_NOT_SUBMITED : ` SELECT ORDER_ID FROM ECOMERCE.ORDERS WHERE USER_ID = ($1) AND  ORDER_SUBMIT = 0   `,

    IS_USER_EXISTS_QUERY : ` SELECT COUNT(USER_ID) AS COUNT FROM ECOMERCE.USERS WHERE LOWER(USERNAME) =LOWER($1) OR LOWER(EMAIL)=LOWER($2) `,

    REGISTER_USER_QUERY : ` INSERT INTO ECOMERCE.USERS (USERNAME, PASSWORD, EMAIL, TOKEN , CREATED_ON,ISADMIN) VALUES($1, $2, $3, $4,$5,$6)  returning *  `,

    LOGIN_QUERY : `  SELECT USER_ID, USERNAME, PASSWORD , EMAIL, TOKEN ,ISADMIN FROM ECOMERCE.USERS WHERE LOWER(USERNAME) = LOWER($1) `,
    UPDATE_TOKEN_QUERY : `UPDATE ECOMERCE.USERS SET TOKEN=$1 WHERE USER_ID=$2`,
}